export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const UNCOMPLETE_TODO = 'UNCOMPLETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const ADD_INGREDIENT_ARRAY = 'ADD_INGREDIENT_ARRAY';

