export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const UNCOMPLETE_TODO = 'UNCOMPLETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const ADD_INGREDIENT_ARRAY = 'ADD_INGREDIENT_ARRAY';
export const ADD_SALES_TO_TODO = 'ADD_SALES_TO_TODO';

export const UPDATE_AMOUNT_OF_INGREDIENTS = 'ALTER_AMOUNT_OF_INGREDIENT';


/*  export enum Actions {
    ADD_TODO,
    REMOVE_TODO,
    TOGGLE_TODO,
    COMPLETE_TODO,
    UNCOMPLETE_TODO,
    EDIT_TODO,
    ADD_INGREDIENT_ARRAY,
    ADD_SALES_TO_TODO,
    ALTER_AMOUNT_OF_INGREDIENT,
}  */